spring:
  application:
    name: test

  thymeleaf:
    suffix: .html
    
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/test?useSSL=false&serverTimezone=UTC
      username: root
      password: 159700
      hikari:
        maximum-pool-size: 10
        connection-timeout: 5000
        connection-init-sql: SELECT 1
        validation-timeout: 2000
        minimum-idle: 10
        idle-timeout: 600000
        max-lifetime: 1800000

server:
  servlet:
    session:
      tracking-modes: cookie